spring:
  application:
    name: scoot
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

rate-limiter:
  limit-for-period: 10
  limit-refresh-period: 1m
  timeout-duration: 25ms

logging:
  level:
    org:
      springframework:
        security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"